version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - alelo_mongo_db
  alelo_mongo_db:
    image: "mongo:4.4.3"
    command: mongod --auth
    restart: always
    volumes:        
        - .init-mongo.js:/docker-entrypoint-initdb.d/
    environment: 
        - MONGO_INITDB_DATABASE=alelo-frota
        - MONGO_INITDB_ROOT_USERNAME=alelo
        - MONGO_INITDB_ROOT_PASSWORD=alelofrota22
    ports:
      - 27017:27017

